<a href="https://colab.research.google.com/github/JairAssisDev/Treinamento-Cin/blob/main/Numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
meu_array= np.array([1,2,3,4,5,6])
print(meu_array)
print(type(meu_array))
print(meu_array.dtype)
print(meu_array[2])

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
int64
3


In [4]:
minha_matriz = np.array([[1,2,3],[4,5,6]])
print(minha_matriz)
print(type(minha_matriz))
print(minha_matriz[0][2])

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
3


In [8]:
escalar = np.array(1)
print(escalar.ndim)

vec1D = np.array([1,2,3])
print(vec1D.ndim)

mat2D = np.array([[1,2,3],[4,5,6]])
print(mat2D.ndim)

mat3D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat3D.ndim)

mat5D = np.array([1,2,3,4,5],ndmin=5)
print(mat5D)
print(mat5D.ndim)


0
1
2
2
[[[[[1 2 3 4 5]]]]]
5


In [9]:
print(escalar.shape)
print(vec1D.shape)
print(mat2D.shape)
print(mat3D.shape)
print(mat5D.shape)

()
(3,)
(2, 3)
(3, 3)
(1, 1, 1, 1, 5)


In [10]:
#número de bits que constituem o valor inteiro: int8, int16, int32, int64
int_array = np.array([1,2,3],dtype= np.int64)
print(int_array)

#número de bits que constituem o valor float: int8, int16, int32, int64
float_array = np.array([1.0,2.0,3.0],dtype=np.float64)
print(float_array)

#array de números complexos
complex_num = np.array([1 + 2j,3- 4],dtype=complex)
print(complex_num)

#array de valores booleanos
bool_array = np.array([True,False,True])
print(bool_array)

#array de strings
string_array = np.array(['foo','bar','baz'],dtype=np.string_)
print(string_array)

#array de datas
date_array =np.array(['2023-01-01','2023-01-02'],dtype=np.datetime64)
print(date_array)


[1 2 3]
[1. 2. 3.]
[ 1.+2.j -1.+0.j]
[ True False  True]
[b'foo' b'bar' b'baz']
['2023-01-01' '2023-01-02']


In [13]:
# Criar uma array vazia com 2 elementos
array_vazia = np.empty(2)
print(array_vazia)

#Criar um array de números inteiros de 0 a 9
array = np.arange(10)
print(array)

#Criar um array de números float de 0 a 1 com incremento de 0.1
array = np.arange(0,1, 0.1)
print(array)

#array de elementos aleatórios
dados_aleatorios = np.random.rand(5)
print(dados_aleatorios)

#Criar um array 2D de zores com 3 linhas e 4 colunas
zeros_array = np.zeros((3,4))
print(zeros_array)

#Criar um array 2D de uns com 2 linha e 3 colunas
uns_array = np.ones((2,3))
print(uns_array)

# criar um array com 10 valores igualmente espeçados entre 1 e 5
array_lins = np.linspace(1,5, num=10)
print(array_lins)

[9.5641e-320 9.5646e-320]
[0 1 2 3 4 5 6 7 8 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.11125056 0.81450963 0.252655   0.20249144 0.78800388]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


In [14]:
arr = np.array([[1,2,3],[4,5,6]])

shape = arr.shape
print(shape)

dimensao = arr.ndim
print(dimensao)

elementos = arr.size
print(elementos)

data_type = arr.dtype
print(data_type)

(2, 3)
2
6
int64


In [15]:
#Operações básicas:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
matriz1 = np.array([[1, 2], [3, 4]])
matriz2 = np.array([[5, 6], [7, 8]])
array_random = np.array([3,6,4,7,4,2])

# soma o elemento na posição correspondente em cada posição
soma = array1 + array2
print(f"Soma de {array1} e {array2}: {soma}")

# subtrai o valor correspondente do segundo array em cada posição
subtracao = array1 - array2
print(f"Subtracao de {array1} e {array2}: {subtracao}")

# multiplica cada elemento do array pelo seu correspondente nem cada posição
multiplicacao = array1 * array2
print(f"multiplicacao {array1} e {array2}: {multiplicacao}")


# divide cada elemento pelo correspondente em cada posição
divisao = array1 / array2
print(f"Divisao de {array1} por {array2}: {divisao}")

# produto entre matrizes:
produto = np.dot(matriz1, matriz2)
print(f"Produto entre {matriz1} e {matriz2}: {produto}")

#concatenando duas arrays
concatenacao = np.concatenate((array1, array2))
print(f"Concatenacao de {array1} e {array2}: {concatenacao}")

#ordenando um array
print(f"Array antes da ordenacao: {array_random}")
array_ordenada = np.sort(array_random)
print(f"Array_ordenado: {array_ordenada}\n")

# podemos adicionar uma dimensão extra de tamanho 1 no array
arr = np.array([[1,2,3],[1,2,3]])
print(f"Expandindo a dimensionalidade")
print(f'Shape: {arr.shape}')
print(f'Shape: {np.expand_dims(arr, axis=0).shape}')
print(f'Shape: {np.expand_dims(arr, axis=1).shape}\n')

# da mesma forma, podemos remover uma dimensao de tamanho 1
arr = np.array([[[1,2,3], [1,2,3]]])
print(f"Revomendo uma dimensao unitaria")
print(f'Shape: {arr.shape}')
print(f'Shape: {np.squeeze(arr, axis=0).shape}\n')

Soma de [1 2 3] e [4 5 6]: [5 7 9]
Subtracao de [1 2 3] e [4 5 6]: [-3 -3 -3]
multiplicacao [1 2 3] e [4 5 6]: [ 4 10 18]
Divisao de [1 2 3] por [4 5 6]: [0.25 0.4  0.5 ]
Produto entre [[1 2]
 [3 4]] e [[5 6]
 [7 8]]: [[19 22]
 [43 50]]
Concatenacao de [1 2 3] e [4 5 6]: [1 2 3 4 5 6]
Array antes da ordenacao: [3 6 4 7 4 2]
Array_ordenado: [2 3 4 4 6 7]

Expandindo a dimensionalidade
Shape: (2, 3)
Shape: (1, 2, 3)
Shape: (2, 1, 3)

Revomendo uma dimensao unitaria
Shape: (1, 2, 3)
Shape: (2, 3)



In [16]:
array = np.array([1, 2, 3, 4, 5, 6, 5, 3, 8])

media = np.mean(array)
print(media)

mediana = np.median(array)
print(mediana)

desvio_padrao = np.std(array)
print(desvio_padrao)

variancia = np.var(array)
print(variancia)

valor_minimo = np.min(array)
valor_maximo = np.max(array)
print(valor_minimo, valor_maximo)

4.111111111111111
4.0
2.0245407953653998
4.098765432098765
1 8


In [17]:
array1 = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#selecionando um intervalo de valores dentro de um array
intervalo = array1[3:8]
print(intervalo)

#selecionando todos os valores pares dentro do array
valores_pares = array1[array1%2==0]
print(valores_pares)

resultados = array1[array1 < 4]
print(resultados)

[4 5 6 7 8]
[ 2  4  6  8 10]
[1 2 3]


# Regressão logistica com Numpy

vamos criar um exemplo do modelo de regressão logistica utilizando o numpy

In [18]:
""" Em programacao Python tradicional
podemos criar o modelo utilizando listas"""

# A entrada eh um vetor de dimensao 10
x = [1,3,2,1,5,2,3,1,6,3]

# temos um valor de peso para cada atributo da entrada
w = [.1, .2, .5, .3, .2, .1, .2, .4, .5, .6]

# e um valor de bias
b = 1.0

modelo_regressao = lambda x: (sum([x[i]*w[i] for i in range(len(x))]) + b)
print(f"Regressao lista: {modelo_regressao(x)}")

""" Agora vamos criar o modelo
utilizando numpy"""

x_np = np.array(x)
w_np = np.array(w)
modelo_regressao_numpy = lambda x: np.sum(x_np * w_np) + b
print(f"Regressao Numpy: {modelo_regressao_numpy(x_np)}")

"""
O processo de otimizacao do modelo de regressao é iterativo e
envolve varios passos
(assim como para varios modelos supervisionados);
Vamos comparar o resultado da operação para varias iterações, simulando
um processo de otimizacao (simplificado)
"""

import time
import random

# vamos criar um vetor de entrada de tramanho 1000 com valores de 0 a 100
x = [random.randint (0, 100) for i in range(1000)]
w = [random.randint (0, 100) for i in range(1000)]

# rodamos o modelo por 1000 iteracoes (epocas)
start = time.time()
for _ in range(1000000): modelo_regressao(x)
end   = time.time()
print(f"Tempo de execucao modelo 01: {end-start}")

x_np = np.array(x)
w_np = np.array(w)
start = time.time()
for _ in range(1000000): modelo_regressao_numpy(x_np)
end   = time.time()
print(f"Tempo de execucao modelo 02: {end-start}")

Regressao lista: 10.0
Regressao Numpy: 10.0
Tempo de execucao modelo 01: 132.98455667495728
Tempo de execucao modelo 02: 9.332834482192993
